language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: true
  directories:
    - .venv

env:
  global:
    - RANDOM_SEED=0
  matrix:
    - FLASK_VERSION=0.10.1
    - FLASK_VERSION=0.11.1
    - FLASK_VERSION=0.12.2
    - FLASK_VERSION=1.0.0

before_install:
  - pip install pipenv

install:
  - make install

before_script:
  - pipenv run pip install flask==${FLASK_VERSION}

script:
  - make check
  - make test

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
