language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: true
  directories:
    - .venv

env:
  global:
  - RANDOM_SEED=0
  - PIPENV_NOSPIN=true
  matrix:
  - FLASK_VERSION=0.10.1
  - FLASK_VERSION=0.11.1
  - FLASK_VERSION=0.12.2

before_install:
  - pip install pipenv~=5.0

install:
  - make install

before_script:
  # Override the version of Flask based on the build matrix
  - pipenv run pip install flask==${FLASK_VERSION}

script:
  - make check
  - make test

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular

notifications:
  email:
    on_success: never
    on_failure: never
