site_name: Flask API
pages:
  - ['index.md', 'Home']
  - ['api-guide/renderers.md', 'API Guide', 'Renderers']
  - ['api-guide/parsers.md', 'API Guide', 'Parsers']
  - ['api-guide/status-codes.md', 'API Guide', 'Status codes']
  - ['about/release-notes.md', 'About', 'Release Notes']
  - ['about/license.md', 'About', 'License']
repo_url: https://github.com/tomchristie/flaskapi
